# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gwcp3.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(710, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 10, 361, 531))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(9)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(370, 10, 331, 441))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButtonLoadBin = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonLoadBin.setObjectName(_fromUtf8("pushButtonLoadBin"))
        self.horizontalLayout_4.addWidget(self.pushButtonLoadBin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButtonLoadDevice = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonLoadDevice.setObjectName(_fromUtf8("pushButtonLoadDevice"))
        self.horizontalLayout_5.addWidget(self.pushButtonLoadDevice)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButtonLiveData = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonLiveData.setObjectName(_fromUtf8("pushButtonLiveData"))
        self.verticalLayout.addWidget(self.pushButtonLiveData)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_8.addWidget(self.label_10)
        self.pushButtonwritedata = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonwritedata.setObjectName(_fromUtf8("pushButtonwritedata"))
        self.horizontalLayout_8.addWidget(self.pushButtonwritedata)
        self.radioButtonCSV = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonCSV.setObjectName(_fromUtf8("radioButtonCSV"))
        self.horizontalLayout_8.addWidget(self.radioButtonCSV)
        self.radioButtonBin = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonBin.setObjectName(_fromUtf8("radioButtonBin"))
        self.horizontalLayout_8.addWidget(self.radioButtonBin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.lineEditsetDev = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditsetDev.sizePolicy().hasHeightForWidth())
        self.lineEditsetDev.setSizePolicy(sizePolicy)
        self.lineEditsetDev.setText(_fromUtf8(""))
        self.lineEditsetDev.setObjectName(_fromUtf8("lineEditsetDev"))
        self.horizontalLayout_12.addWidget(self.lineEditsetDev)
        self.listWidgetspeed = QtGui.QListWidget(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetspeed.sizePolicy().hasHeightForWidth())
        self.listWidgetspeed.setSizePolicy(sizePolicy)
        self.listWidgetspeed.setObjectName(_fromUtf8("listWidgetspeed"))
        item = QtGui.QListWidgetItem()
        self.listWidgetspeed.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetspeed.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetspeed.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetspeed.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetspeed.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetspeed.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetspeed.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetspeed.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetspeed.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidgetspeed.addItem(item)
        self.horizontalLayout_12.addWidget(self.listWidgetspeed)
        self.pushButtonSerialSet = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSerialSet.sizePolicy().hasHeightForWidth())
        self.pushButtonSerialSet.setSizePolicy(sizePolicy)
        self.pushButtonSerialSet.setObjectName(_fromUtf8("pushButtonSerialSet"))
        self.horizontalLayout_12.addWidget(self.pushButtonSerialSet)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pushButtongetTime = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtongetTime.setObjectName(_fromUtf8("pushButtongetTime"))
        self.horizontalLayout_13.addWidget(self.pushButtongetTime)
        self.lineEditgetTime = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEditgetTime.setObjectName(_fromUtf8("lineEditgetTime"))
        self.horizontalLayout_13.addWidget(self.lineEditgetTime)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_14.addWidget(self.label_13)
        self.lineEditSystemTime = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEditSystemTime.setObjectName(_fromUtf8("lineEditSystemTime"))
        self.horizontalLayout_14.addWidget(self.lineEditSystemTime)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_131 = QtGui.QHBoxLayout()
        self.horizontalLayout_131.setObjectName(_fromUtf8("horizontalLayout_131"))
        self.pushButtonsetTime = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonsetTime.setObjectName(_fromUtf8("pushButtonsetTime"))
        self.horizontalLayout_131.addWidget(self.pushButtonsetTime)
        self.verticalLayout_4.addLayout(self.horizontalLayout_131)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionLjlkj = QtGui.QAction(MainWindow)
        self.actionLjlkj.setObjectName(_fromUtf8("actionLjlkj"))
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "GMC Datalogger", None))
        self.label_9.setText(_translate("MainWindow", "GMC-3xx Datalogger", None))
        self.pushButtonLoadBin.setText(_translate("MainWindow", "Load binary data from file", None))
        self.pushButtonLoadDevice.setText(_translate("MainWindow", "Load history data from device", None))
        self.pushButton.setText(_translate("MainWindow", "Show data", None))
        self.checkBox.setText(_translate("MainWindow", "With Tags", None))
        self.pushButtonLiveData.setToolTip(_translate("MainWindow", "(not implemented)", None))
        self.pushButtonLiveData.setText(_translate("MainWindow", "Live data", None))
        self.label_10.setText(_translate("MainWindow", "Save to file:", None))
        self.pushButtonwritedata.setToolTip(_translate("MainWindow", "Write data to file.", None))
        self.pushButtonwritedata.setText(_translate("MainWindow", "Write data", None))
        self.radioButtonCSV.setToolTip(_translate("MainWindow", "Save text file", None))
        self.radioButtonCSV.setText(_translate("MainWindow", "CSV", None))
        self.radioButtonBin.setToolTip(_translate("MainWindow", "Save binary file in device format", None))
        self.radioButtonBin.setText(_translate("MainWindow", "Binary", None))
        self.lineEditsetDev.setToolTip(_translate("MainWindow", "serial interface  name", None))
        self.listWidgetspeed.setToolTip(_translate("MainWindow", "Baud rate", None))
        __sortingEnabled = self.listWidgetspeed.isSortingEnabled()
        self.listWidgetspeed.setSortingEnabled(False)
        item = self.listWidgetspeed.item(0)
        item.setText(_translate("MainWindow", "115200", None))
        item = self.listWidgetspeed.item(1)
        item.setText(_translate("MainWindow", "57600", None))
        item = self.listWidgetspeed.item(2)
        item.setText(_translate("MainWindow", "38400", None))
        item = self.listWidgetspeed.item(3)
        item.setText(_translate("MainWindow", "28800", None))
        item = self.listWidgetspeed.item(4)
        item.setText(_translate("MainWindow", "19200", None))
        item = self.listWidgetspeed.item(5)
        item.setText(_translate("MainWindow", "14400", None))
        item = self.listWidgetspeed.item(6)
        item.setText(_translate("MainWindow", "9600", None))
        item = self.listWidgetspeed.item(7)
        item.setText(_translate("MainWindow", "4800", None))
        item = self.listWidgetspeed.item(8)
        item.setText(_translate("MainWindow", "2400", None))
        item = self.listWidgetspeed.item(9)
        item.setText(_translate("MainWindow", "1200", None))
        self.listWidgetspeed.setSortingEnabled(__sortingEnabled)
        self.pushButtonSerialSet.setToolTip(_translate("MainWindow", "Set serial connection", None))
        self.pushButtonSerialSet.setText(_translate("MainWindow", "Serial", None))
        self.pushButtongetTime.setToolTip(_translate("MainWindow", "Get device date and time", None))
        self.pushButtongetTime.setText(_translate("MainWindow", "Get time", None))
        self.lineEditgetTime.setToolTip(_translate("MainWindow", "Device Time", None))
        self.label_13.setText(_translate("MainWindow", "System time", None))
        self.lineEditSystemTime.setToolTip(_translate("MainWindow", "System time", None))
        self.pushButtonsetTime.setToolTip(_translate("MainWindow", "Set device date and time", None))
        self.pushButtonsetTime.setText(_translate("MainWindow", "Set device to system time", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionQuit.setText(_translate("MainWindow", "&Quit", None))
        self.actionHelp.setText(_translate("MainWindow", "Show Helpfile", None))
        self.actionLjlkj.setText(_translate("MainWindow", "ljlkj", None))

